version: '3'
services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./data/redis:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"