### create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "corrolla",
    "year": 1980,
    "mileage": 100000,
    "lng": 0,
    "lat": 0,
    "price": 50000
}

### approved report
PATCH  http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}

### get estimate
GET  http://localhost:3000/reports?make=toyota&model=corrolla&lng=0&lat=0&mileage=20000&year=1980