# ---- Base Node ----
    FROM node:18 AS base
    WORKDIR /app
    COPY package*.json ./
    
    # ---- Dependencies ----
    FROM base AS dependencies
    RUN npm install
    # ---- Build ----
    FROM base AS build
    COPY . ./
    COPY --from=dependencies /app/node_modules ./node_modules
    RUN npm run build
    # ---- Release Distroless ----
    FROM gcr.io/distroless/nodejs18-debian11

    WORKDIR /app
    COPY --from=build /app .
    CMD ["dist/main.js"]